# Generated by Django 3.1 on 2021-07-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20210718_1024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Project Admin'), (2, 'Project Manager'), (3, 'Project Leader'), (4, 'Member'), (5, 'Custom')], default=4)),
                ('is_active', models.BooleanField(default=True, verbose_name='invite_active')),
                ('status', models.CharField(choices=[('Invited', 'Onhold'), ('Joined', 'Joined'), ('Leave', 'Leaved'), ('Declined', 'Declined')], default='Invited', max_length=120, verbose_name='invite status')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
    ]
