# Generated by Django 3.1 on 2021-08-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_auto_20210719_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together=set(),
        ),
    ]
