# Generated by Django 3.1 on 2021-07-18 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20210718_2223'),
        ('collaborator', '0003_auto_20210719_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='collaborator',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together={('name', 'project')},
        ),
    ]
