//User authentication 

export const AUTH_START =  'AUTH_START'
export const AUTH_SUCCESS =  'AUTH_SUCCESS'
export const AUTH_FAIL =  'AUTH_FAIL'
export const AUTH_REFRESH =  'AUTH_REFRESH'
export const AUTH_LOGOUT =  'AUTH_LOGOUT'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL'


export const SET_REDIRECT = 'SET_REDIRECT'

//user

export const GETOWNERDATA_SUCCESS = 'GETOWNERDATA_SUCCESS'
export const GETOWNERDATA_FAIL = 'GETOWNERDATA_FAIL'
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS'
export const GETUSER_FAIL = 'GETUSER_FAIL'


//counter 

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

//dashboard 
export const OPENMENU = 'OPENMENU'
export const CLOSEMENU = 'CLOSEMENU'

export const OPENDRAWER = 'OPENDRAWER'
export const CLOSEDRAWER = 'CLOSEDRAWER'

export const OPENDRAWERMENU = 'OPENDRAWERMENU'
export const CLOSEDRAWERMENU = 'CLOSEDRAWERMENU'


// project
export const GETPROJECTLIST_SUCCESS = 'GETPROJECTLIST_SUCCESS'
export const GETPROJECTDETAILS_SUCCESS = 'GETPROJECTDETAILS_SUCCESS'
export const ADDPROJECT_SUCCESS = 'ADDPROJECT_SUCCESS'
export const UPDATEPROJECT_SUCCESS = 'UPDATEPROJECT_SUCCESS'
export const DELETEPROJECT_SUCCESS = 'DELETEPROJECT_SUCCESS'

export const GETPROJECTLIST_FAIL = 'GETPROJECTLIST_FAIL'
export const GETPROJECTDETAILS_FAIL = 'GETPROJECTDETAILS_FAIL'
export const ADDPROJECT_FAIL = 'ADDPROJECT_FAIL'
export const UPDATEPROJECT_FAIL = 'UPDATEPROJECT_FAIL'
export const DELETEPROJECT_FAIL = 'DELETEPROJECT_FAIL'


export const GETJOINEDPROJECTLIST_SUCCESS = 'GETJOINEDPROJECTLIST_SUCCESS'
export const GETJOINEDPROJECTDETAILS_SUCCESS = 'GETJOINEDPROJECTDETAILS_SUCCESS'

//associate
export const GETASSOCIATELIST_SUCCESS = 'GETASSOCIATELIST_SUCCESS'
export const GETASSOCIATEDETAILS_SUCCESS = 'GETASSOCIATEDETAILS_SUCCESS'
export const ADDASSOCIATE_SUCCESS = 'ADDASSOCIATE_SUCCESS'
export const UPDATEASSOCIATE_SUCCESS = 'UPDATEASSOCIATE_SUCCESS'
export const DELETEASSOCIATE_SUCCESS = 'DELETEASSOCIATE_SUCCESS'

export const GETASSOCIATELIST_FAIL = 'GETASSOCIATELIST_FAIL'
export const GETASSOCIATEDETAILS_FAIL = 'GETASSOCIATEDETAILS_FAIL'
export const ADDASSOCIATE_FAIL = 'ADDASSOCIATE_FAIL'
export const UPDATEASSOCIATE_FAIL = 'UPDATEASSOCIATE_FAIL'
export const DELETEASSOCIATE_FAIL = 'DELETEASSOCIATE_FAIL'

// collaborator
export const GETCOLLABORATORLIST_SUCCESS = 'GETCOLLABORATORLIST_SUCCESS'
export const GETCOLLABORATORDETAILS_SUCCESS = 'GETCOLLABORATORDETAILS_SUCCESS'
export const ADDCOLLABORATOR_SUCCESS = 'ADDCOLLABORATOR_SUCCESS'
export const UPDATECOLLABORATORPOSITION_SUCCESS = 'UPDATECOLLABORATORPOSITION_SUCCESS'
export const REMOVECOLLABORATOR_SUCCESS = 'REMOVECOLLABORATOR_SUCCESS'

export const GETCOLLABORATORLIST_FAIL = 'GETCOLLABORATORLIST_FAIL'
export const GETCOLLABORATORDETAILS_FAIL = 'GETCOLLABORATORDETAILS_FAIL'
export const ADDCOLLABORATOR_FAIL = 'ADDCOLLABORATOR_FAIL'
export const UPDATECOLLABORATORPOSITION_FAIL = 'UPDATECOLLABORATORPOSITION_FAIL'
export const REMOVECOLLABORATOR_FAIL = 'REMOVECOLLABORATOR_FAIL'

//activity
export const GETACTIVITYLIST_SUCCESS = 'GETACTIVITYLIST_SUCCESS'
export const GETACTIVITYDETAILS_SUCCESS = 'GETACTIVITYDETAILS_SUCCESS'
export const ADDACTIVITY_SUCCESS = 'ADDACTIVITY_SUCCESS'
export const UPDATEACTIVITY_SUCCESS = 'UPDATEACTIVITY_SUCCESS'
export const DELETEACTIVITY_SUCCESS = 'DELETEACTIVITY_SUCCESS'

export const GETACTIVITYLIST_FAIL = 'GETACTIVITYLIST_FAIL'
export const GETACTIVITYDETAILS_FAIL = 'GETACTIVITYDETAILS_FAIL'
export const ADDACTIVITY_FAIL = 'ADDACTIVITY_FAIL'
export const UPDATEACTIVITY_FAIL = 'UPDATEACTIVITY_FAIL'
export const DELETEACTIVITY_FAIL = 'DELETEACTIVITY_FAIL'

//task
export const GETTASKLIST_SUCCESS = 'GETTASKLIST_SUCCESS'
export const GETTASKDETAILS_SUCCESS = 'GETTASKDETAILS_SUCCESS'
export const ADDTASK_SUCCESS = 'ADDTASK_SUCCESS'
export const UPDATETASK_SUCCESS = 'UPDATETASK_SUCCESS'
export const DELETETASK_SUCCESS = 'DELETETASK_SUCCESS'

export const GETTASKLIST_FAIL = 'GETTASKLIST_FAIL'
export const GETTASKDETAILS_FAIL = 'GETTASKDETAILS_FAIL'
export const ADDTASK_FAIL = 'ADDTASK_FAIL'
export const UPDATETASK_FAIL = 'UPDATETASK_FAIL'
export const DELETETASK_FAIL = 'DELETETASK_FAIL'

