# Generated by Django 3.1 on 2021-07-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='invitation active')),
                ('status', models.CharField(choices=[('Waiting', 'Onhold'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Dissociated', 'Dissociated')], default='Waiting', max_length=50, verbose_name='invite status')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Associate',
                'verbose_name_plural': 'Associates',
                'db_table': '',
                'managed': True,
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
