# Generated by Django 3.1 on 2021-08-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='invitation active')),
                ('status', models.CharField(blank=True, choices=[('Waiting', 'Onhold'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Dissociated', 'Dissociated')], max_length=50, null=True, verbose_name='invite status')),
            ],
            options={
                'verbose_name': 'Associate',
                'verbose_name_plural': 'Associates',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
