# Generated by Django 3.1 on 2021-07-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0002_auto_20210719_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting', 'Onhold'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Dissociated', 'Dissociated')], max_length=50, null=True, verbose_name='invite status'),
        ),
    ]
