# Generated by Django 3.1 on 2021-08-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associate', '0003_auto_20210720_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
    ]
