# Generated by Django 3.1 on 2021-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_created_by'),
        ('activity', '0002_auto_20210718_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task.Task', verbose_name='task'),
        ),
    ]
