# Generated by Django 3.1 on 2021-07-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210718_2223'),
        ('activity', '0003_auto_20210718_2223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('name', 'project')},
        ),
    ]
