# Generated by Django 3.1 on 2021-07-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desciption', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='task start date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='task due date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('importance', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3)),
                ('patch', models.PositiveSmallIntegerField(blank=True, choices=[(1001, 'DASHED01'), (1002, 'DASHED02'), (1003, 'DASHED03'), (1004, 'DASHED04'), (1005, 'DASHED05'), (2001, 'DOTTED01'), (2002, 'DOTTED02'), (2003, 'DOTTED03'), (2004, 'DOTTED04'), (2005, 'DOTTED05'), (3001, 'SOLID01'), (3002, 'SOLID02'), (3003, 'SOLID03'), (3004, 'SOLID04'), (3005, 'SOLID05')], null=True, verbose_name='task line & color marking(patch)')),
                ('activity', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
