# Generated by Django 3.1 on 2021-07-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
