# Generated by Django 3.1 on 2021-07-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(blank=True, max_length=120, null=True, verbose_name='project_name_slug')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'On-Hold'), (3, 'Completed'), (4, 'Delivered')], default=1, verbose_name='project status')),
                ('project_type', models.PositiveSmallIntegerField(choices=[(2, 'Software Development'), (3, 'Equipment / System Installation')], default=2, verbose_name='project type')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Project Admin'), (2, 'Project Manager'), (3, 'Project Leader'), (4, 'Member'), (5, 'Custom')], default=4)),
                ('is_active', models.BooleanField(default=True, verbose_name='invite_active')),
                ('status', models.CharField(choices=[('Invited', 'Onhold'), ('Joined', 'Joined'), ('Leave', 'Leaved'), ('Declined', 'Declined')], default='Invited', max_length=120, verbose_name='invite status')),
            ],
            options={
                'verbose_name': 'ProjectMember',
                'verbose_name_plural': 'ProjectMembers',
            },
        ),
    ]
