# Generated by Django 3.1 on 2021-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(blank=True, max_length=120, null=True, verbose_name='project_name_slug')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'On-Hold'), (3, 'Completed'), (4, 'Delivered')], default=1, verbose_name='project status')),
                ('project_type', models.PositiveSmallIntegerField(choices=[(2, 'Software Development'), (3, 'Equipment / System Installation')], default=2, verbose_name='project type')),
                ('activities', models.ManyToManyField(blank=True, related_name='activity', to='activity.Activity', verbose_name='activity')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborator', to='collaborator.Collaborator', verbose_name='collaborator')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
