# Generated by Django 3.1 on 2021-07-18 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210718_2223'),
        ('user', '0002_customuser_associates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associates',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='associates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='project_list', to='project.Project', verbose_name='projects'),
        ),
    ]
