# Generated by Django 3.1 on 2021-07-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210719_1940'),
        ('user', '0002_customuser_joined_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined_projects',
            field=models.ManyToManyField(blank=True, default=[0], related_name='joined_projects', to='project.Project', verbose_name='projects joined'),
        ),
    ]
